name: Render Plantuml
on: [push, pull_request]
jobs:
  build:    
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:  
    - name: Render PlantUML to wiki
      uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
      with:
        WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
        INPUT_DIR: 'path/to/input_directory'
        OUTPUT_DIR: 'path/to/output_directory'
